#ifndef __PYHELLO_GEN__
#define __PYHELLO_GEN__

#include "SALOME_Component.idl"
#include "SALOMEDS.idl"
#include "SALOME_Exception.idl"

module PYHELLO_ORB
{
  interface PYHELLO_Gen : Engines::Component, SALOMEDS::Driver
  {
     string makeBanner(in string name)
         raises (SALOME::SALOME_Exception);
  };
};

#endif
